[project]
name = "ddx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
authors = [{name = "Diddigam Sai Praneeth", email = "johndoeknown@protonmail.com"}]
dependencies = [
    "openai>=1.58.1",
]
